# Generated by Django 4.2.18 on 2025-01-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='getir_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='migros_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='trendyol_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='yemeksepeti_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
