# Generated by Django 4.2.18 on 2025-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_branch_getir_url_branch_migros_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
