# Generated by Django 4.2.18 on 2025-02-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_branch_getir_status_branch_migros_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='migros_status',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='migros_url',
        ),
    ]
