# Generated by Django 4.2.18 on 2025-02-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_branch_migros_status_remove_branch_migros_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='migros_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='migros_restaurant_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='migros_status',
            field=models.BooleanField(default=False),
        ),
    ]
