# Generated by Django 4.2.18 on 2025-02-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_branch_migros_api_key_branch_migros_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='trendyol_status',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='trendyol_url',
        ),
    ]
