# Generated by Django 4.2.18 on 2025-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_branch_trendyol_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='trendyol_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='trendyol_api_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='trendyol_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='trendyol_supplier_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
