# Generated by Django 4.2.18 on 2025-02-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_branch_trendyol_api_key_branch_trendyol_api_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='previous_getir_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='previous_migros_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='previous_trendyol_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='previous_yemeksepeti_status',
            field=models.BooleanField(default=False),
        ),
    ]
