# Generated by Django 4.2.18 on 2025-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_branch_notification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram kullanıcı adı (@username)', max_length=100),
        ),
    ]
